const $ = (id) => document.getElementById(id);
const tagOptions = {
  allowed_sound_directions: ["ambient", "acoustic", "organic", "vintage", "electronic", "ethnic", "cinematic"],
  allowed_emotions: ["深沉", "阴郁", "忧伤", "平静", "温暖", "明亮", "欢快", "激昂"],
  allowed_energy: ["静止", "高能", "流动"],
  allowed_rhythm: ["sparse", "flow", "standard", "groove", "aggressive"],
  allowed_rhythm_profiles: ["house_groove", "edm_drive", "trap_hybrid"]
};
const degreeOptions = ["root", "fifth", "octave", "octave_root", "diatonic_passing", "chromatic_approach", "next_root_pickup", "next_root", "ghost_root", "ghost_fifth", "rest"];
const previewRoots = [36, 33, 29, 31];
let modes = [];
let audioContext;

function status(text) { $("status-line").textContent = text; }
async function request(url, options = {}) { const response = await fetch(url, options); const payload = await response.json(); if (!response.ok || !payload.ok) throw new Error(payload.error || "请求失败"); return payload; }
function modeCard(id) { return document.querySelector(`[data-mode-id="${id}"]`); }
function tags(mode, field) { return tagOptions[field].map((tag) => `<button type="button" class="choice ${mode[field]?.includes(tag) ? "active" : ""}" data-tag-field="${field}" data-tag-value="${tag}">${tag}</button>`).join(""); }
function variantMarkup(variant, index) {
  return `<section class="panel" data-variant-index="${index}" style="padding:12px; margin-top:10px"><div class="pattern-card-head"><label class="field" style="min-width:190px"><span>Pattern Variant ${String.fromCharCode(65 + index)}</span><input data-variant-name value="${variant.name || ""}" /></label><label class="switch"><input data-variant-enabled type="checkbox" ${variant.enabled !== false ? "checked" : ""} /> 启用</label></div><div class="event-list">${(variant.events || []).map(eventMarkup).join("")}</div><button type="button" data-add-event>+ 添加音符</button></section>`;
}
function eventMarkup(event = { step: 0, degree: "root", duration_steps: 2, velocity_multiplier: 1, probability: 1, enabled: true }) {
  return `<div class="four-col" data-event style="margin-top:8px"><label class="field"><span>Step</span><input data-event-step type="number" min="0" max="15" value="${event.step}" /></label><label class="field"><span>音级</span><select data-event-degree>${degreeOptions.map((degree) => `<option value="${degree}" ${event.degree === degree ? "selected" : ""}>${degree}</option>`).join("")}</select></label><label class="field"><span>长度 (step)</span><input data-event-duration type="number" min="1" max="16" value="${event.duration_steps}" /></label><label class="field"><span>力度</span><input data-event-velocity type="number" min="0.1" max="1.2" step="0.05" value="${event.velocity_multiplier || 1}" /></label><label class="field"><span>概率</span><input data-event-probability type="number" min="0" max="1" step="0.05" value="${event.probability ?? 1}" /></label><label class="switch"><input data-event-glide type="checkbox" ${event.glide ? "checked" : ""} /> Glide</label><button type="button" data-remove-event title="删除此音符">删除</button></div>`;
}
function modeMarkup(mode) {
  const electronic = mode.category === "electronic";
  const cinematic = mode.category === "cinematic";
  const glideControls = electronic ? `<div class="three-col" style="margin-top:10px"><label class="switch"><input data-field="glide_enabled" type="checkbox" ${mode.glide_enabled ? "checked" : ""} /> Glide Enabled</label><label class="field"><span>Glide Time (ms)</span><input data-field="glide_time_ms" type="number" min="0" max="300" value="${mode.glide_time_ms ?? 0}" /></label><label class="field"><span>Pitch Bend Range</span><input data-field="pitch_bend_range" type="number" min="0" max="24" value="${mode.pitch_bend_range ?? 2}" /></label></div>` : "";
  const profileTags = electronic ? `<div class="tag-block"><span>允许电子节奏档案</span><div class="choice-grid">${tags(mode, "allowed_rhythm_profiles")}</div></div>` : "";
  const cinematicControls = cinematic ? `<div class="two-col" style="margin-top:10px"><label class="field"><span>持续</span><input data-field="sustain" type="number" min="0.05" max="1" step="0.05" value="${mode.sustain ?? mode.duration_ratio}" /></label><label class="switch"><input data-field="harmony_follow" type="checkbox" ${mode.harmony_follow ? "checked" : ""} /> 跟随和声变化</label></div><div class="tag-block"><span>允许情绪</span><div class="choice-grid">${tags(mode, "allowed_emotions")}</div></div>` : "";
  return `<article class="foundation-pattern-card" data-mode-id="${mode.id}"><div style="width:100%"><div class="pattern-card-head"><div><b>${mode.label}</b><small>${mode.name} · ${mode.description}</small></div><label class="switch"><input data-field="enabled" type="checkbox" ${mode.enabled ? "checked" : ""} /> 启用</label></div><div class="four-col" style="margin-top:12px"><label class="field"><span>Grid</span><select data-field="grid"><option ${mode.grid === "1/4" ? "selected" : ""}>1/4</option><option ${mode.grid === "1/8" ? "selected" : ""}>1/8</option><option ${mode.grid === "1/16" ? "selected" : ""}>1/16</option><option ${mode.grid === "1/2 bar" ? "selected" : ""}>1/2 bar</option><option ${mode.grid === "1 bar" ? "selected" : ""}>1 bar</option></select></label><label class="field"><span>音符长度</span><input data-field="duration_ratio" type="number" min="0.05" max="1" step="0.05" value="${mode.duration_ratio}" /></label><label class="field"><span>Timing</span><input data-field="timing_amount" type="number" min="0" max="0.2" step="0.01" value="${mode.timing_amount}" /></label><label class="field"><span>优先级</span><input data-field="priority" type="number" min="0" max="999" value="${mode.priority}" /></label></div><div class="two-col" style="margin-top:10px"><label class="field"><span>最低力度</span><input data-velocity-min type="number" min="1" max="127" value="${mode.velocity_range?.[0] || 60}" /></label><label class="field"><span>最高力度</span><input data-velocity-max type="number" min="1" max="127" value="${mode.velocity_range?.[1] || 90}" /></label></div>${glideControls}${cinematicControls}<label class="field" style="margin-top:10px"><span>允许音级</span><input data-allowed-degrees value="${(mode.allowed_degrees || []).join(", ")}" /></label><div class="tag-sections"><div class="tag-block"><span>允许音色方向</span><div class="choice-grid">${tags(mode, "allowed_sound_directions")}</div></div><div class="tag-block"><span>允许能量</span><div class="choice-grid">${tags(mode, "allowed_energy")}</div></div><div class="tag-block"><span>允许节奏</span><div class="choice-grid">${tags(mode, "allowed_rhythm")}</div></div>${profileTags}</div><div class="variants">${(mode.variants || []).slice(0, 4).map(variantMarkup).join("")}</div></div><div class="actions"><button type="button" data-preview="${mode.id}">试听 4 小节</button></div></article>`;
}
function render() {
  const standard = modes.filter((mode) => !["electronic", "ethnic", "cinematic"].includes(mode.category)).map(modeMarkup).join("");
  const electronic = modes.filter((mode) => mode.category === "electronic").map(modeMarkup).join("");
  const ethnic = modes.filter((mode) => mode.category === "ethnic").map(modeMarkup).join("");
  const cinematic = modes.filter((mode) => mode.category === "cinematic").map(modeMarkup).join("");
  $("mode-list").innerHTML = `${standard}${electronic ? `<h2 style="margin:30px 0 10px">Electronic Bass</h2><p class="hint">电子专用：House 四拍低音与 808 切分低音。</p>${electronic}` : ""}${ethnic ? `<h2 style="margin:30px 0 10px">民族 Bass</h2><p class="hint">中东与世界音乐专用：持续 Drone 与 Darbuka 脉冲。</p>${ethnic}` : ""}${cinematic ? `<h2 style="margin:30px 0 10px">电影 Bass</h2><p class="hint">低频重量与和声推进：长音、少变化，不生成流行 Bass Groove。</p>${cinematic}` : ""}`;
  document.querySelectorAll("[data-tag-field]").forEach((button) => button.addEventListener("click", () => button.classList.toggle("active")));
  document.querySelectorAll("[data-add-event]").forEach((button) => button.addEventListener("click", () => button.closest("[data-variant-index]").querySelector(".event-list").insertAdjacentHTML("beforeend", eventMarkup())));
  document.querySelectorAll("[data-remove-event]").forEach((button) => button.addEventListener("click", () => button.closest("[data-event]").remove()));
  document.querySelectorAll("[data-preview]").forEach((button) => button.addEventListener("click", () => preview(button.dataset.preview)));
}
function selectedTags(card, field) { return [...card.querySelectorAll(`[data-tag-field="${field}"].active`)].map((item) => item.dataset.tagValue); }
function eventValues(row) { return { step: Number(row.querySelector("[data-event-step]").value), degree: row.querySelector("[data-event-degree]").value, duration_steps: Number(row.querySelector("[data-event-duration]").value), velocity_multiplier: Number(row.querySelector("[data-event-velocity]").value), probability: Number(row.querySelector("[data-event-probability]").value), glide: row.querySelector("[data-event-glide]").checked, enabled: true }; }
function currentModes() { return modes.map((mode) => { const card = modeCard(mode.id); return { ...mode, enabled: card.querySelector('[data-field="enabled"]').checked, grid: card.querySelector('[data-field="grid"]').value, duration_ratio: Number(card.querySelector('[data-field="duration_ratio"]').value), sustain: Number(card.querySelector('[data-field="sustain"]')?.value || mode.sustain || mode.duration_ratio), harmony_follow: card.querySelector('[data-field="harmony_follow"]')?.checked || false, timing_amount: Number(card.querySelector('[data-field="timing_amount"]').value), priority: Number(card.querySelector('[data-field="priority"]').value), velocity_range: [Number(card.querySelector("[data-velocity-min]").value), Number(card.querySelector("[data-velocity-max]").value)], allowed_degrees: card.querySelector("[data-allowed-degrees]").value.split(",").map((item) => item.trim()).filter((item) => degreeOptions.includes(item)), allowed_sound_directions: selectedTags(card, "allowed_sound_directions"), allowed_emotions: mode.category === "cinematic" ? selectedTags(card, "allowed_emotions") : [], allowed_energy: selectedTags(card, "allowed_energy"), allowed_rhythm: selectedTags(card, "allowed_rhythm"), allowed_rhythm_profiles: mode.category === "electronic" ? selectedTags(card, "allowed_rhythm_profiles") : [], glide_enabled: card.querySelector('[data-field="glide_enabled"]')?.checked || false, glide_time_ms: Number(card.querySelector('[data-field="glide_time_ms"]')?.value || 0), pitch_bend_range: Number(card.querySelector('[data-field="pitch_bend_range"]')?.value || 0), variants: [...card.querySelectorAll("[data-variant-index]")].map((variant, index) => ({ ...mode.variants[index], name: variant.querySelector("[data-variant-name]").value.trim() || mode.variants[index].name, enabled: variant.querySelector("[data-variant-enabled]").checked, events: [...variant.querySelectorAll("[data-event]")].map(eventValues) })) }; }); }
function degreePitch(degree, root, nextRoot) { if (degree === "fifth" || degree === "ghost_fifth") return root + 7; if (["octave", "octave_root"].includes(degree)) return root + 12; if (degree === "next_root") return nextRoot; if (["next_root_pickup", "chromatic_approach"].includes(degree)) return nextRoot > root ? nextRoot - 1 : nextRoot + 1; if (degree === "diatonic_passing") return root + (nextRoot >= root ? 2 : -2); return root; }
function preview(modeId) { const mode = currentModes().find((item) => item.id === modeId); if (!mode) return; const variant = mode.variants.find((item) => item.enabled) || mode.variants[0]; if (!variant) return; audioContext ||= new AudioContext(); const stepSeconds = 60 / Number($("preview-bpm").value || 96) / 4; const now = audioContext.currentTime + .05; for (let bar = 0; bar < 4; bar += 1) { const root = previewRoots[bar], nextRoot = previewRoots[(bar + 1) % 4]; for (const event of variant.events) { if (event.degree === "rest") continue; const start = now + (bar * 16 + event.step) * stepSeconds; const oscillator = audioContext.createOscillator(); const gain = audioContext.createGain(); oscillator.type = "triangle"; oscillator.frequency.value = 440 * 2 ** ((degreePitch(event.degree, root, nextRoot) - 69) / 12); const length = Math.max(.04, event.duration_steps * stepSeconds * mode.duration_ratio); gain.gain.setValueAtTime(.0001, start); gain.gain.exponentialRampToValueAtTime(.06 * event.velocity_multiplier, start + .01); gain.gain.exponentialRampToValueAtTime(.0001, start + length); oscillator.connect(gain).connect(audioContext.destination); oscillator.start(start); oscillator.stop(start + length + .03); } } status(`正在试听 ${mode.label} · ${variant.name}`); }
async function load() { const payload = await request("/api/bass-groove-modes"); modes = payload.modes || []; render(); status(`已加载 ${modes.length} 个 Bass 律动模式`); }
$("save").addEventListener("click", async () => { try { const payload = await request("/api/bass-groove-modes/save", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ modes: currentModes() }) }); modes = payload.modes || []; render(); status("已保存。Loop 控制台下一次生成将使用这些 Bass 模式。"); } catch (error) { status(error.message); } });
$("reset").addEventListener("click", async () => { if (!confirm("恢复全部 Bass 律动模式为默认设置？")) return; try { const payload = await request("/api/bass-groove-modes/reset", { method: "POST" }); modes = payload.modes || []; render(); status("已恢复默认设置"); } catch (error) { status(error.message); } });
load().catch((error) => status(error.message));
