const $ = (id) => document.getElementById(id);
const degrees = ["root", "third", "fifth", "seventh", "ninth", "octave_root", "octave_third", "octave_fifth", "next_root", "next_fifth"];
const playModes = [["single", "单音拨奏"], ["stack", "和弦齐奏"], ["roll_up", "向上错峰"], ["roll_down", "向下错峰"]];
const tags = { guitar: ["nylon", "electric"], sound: ["ambient", "acoustic", "organic", "vintage", "electronic", "ethnic", "cinematic"], energy: ["静止", "高能", "流动"], rhythm: ["sparse", "flow", "standard", "groove", "aggressive"] };
let modes = [], selectedId = "", selectedVariant = "";
let previewAudioContext = null;
const esc = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]));
async function request(url, options = {}) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.error || "请求失败"); return data; }
function current() { return modes.find((mode) => mode.id === selectedId) || modes[0]; }
function variant() { const mode = current(); return mode?.variants?.find((item) => item.id === selectedVariant) || mode?.variants?.[0]; }
function choices(key, values) { const item = current(); return tags[key].map((value) => `<label><input type="checkbox" data-tag="${key}" value="${value}" ${values.includes(value) ? "checked" : ""}>${value}</label>`).join(""); }
function renderList() { $("mode-list").innerHTML = modes.map((mode) => `<button data-mode="${mode.id}" class="${mode.id === current()?.id ? "active" : ""}"><b>${esc(mode.label)}</b><br><small>${esc(mode.description)}</small></button>`).join(""); document.querySelectorAll("[data-mode]").forEach((button) => button.onclick = () => { selectedId = button.dataset.mode; selectedVariant = current()?.variants?.[0]?.id || ""; render(); }); }
function render() {
  const mode = current(); if (!mode) return;
  selectedId = mode.id; selectedVariant ||= mode.variants?.[0]?.id || "";
  renderList();
  const active = variant();
  $("editor").innerHTML = `
    <div class="editor-grid">
      <label class="field"><span>模式名称</span><input data-field="label" value="${esc(mode.label)}"></label>
      <label class="field"><span>英文名称</span><input data-field="name" value="${esc(mode.name)}"></label>
      <label class="field"><span>Grid</span><select data-field="grid"><option ${mode.grid === "1/4" ? "selected" : ""}>1/4</option><option ${mode.grid === "1/8" ? "selected" : ""}>1/8</option><option ${mode.grid === "1/16" ? "selected" : ""}>1/16</option></select></label>
      <label class="field"><span>优先级</span><input data-field="priority" type="number" value="${mode.priority}"></label>
      <label class="field"><span>时值比例</span><input data-field="duration_ratio" type="number" min="0.05" max="1" step="0.05" value="${mode.duration_ratio}"></label>
      <label class="field"><span>最低力度</span><input data-velocity="0" type="number" min="1" max="127" value="${mode.velocity_range?.[0] ?? 60}"></label>
      <label class="field"><span>最高力度</span><input data-velocity="1" type="number" min="1" max="127" value="${mode.velocity_range?.[1] ?? 90}"></label>
      <label class="field"><span>时值浮动</span><input data-field="timing_amount" type="number" min="0" max="0.2" step="0.005" value="${mode.timing_amount}"></label>
      <label class="field"><span>力度浮动</span><input data-field="velocity_amount" type="number" min="0" max="0.3" step="0.01" value="${mode.velocity_amount}"></label>
      <label class="field"><span>最低八度</span><input data-octave="0" type="number" min="1" max="6" value="${mode.octave_range?.[0] ?? 3}"></label>
      <label class="field"><span>最高八度</span><input data-octave="1" type="number" min="1" max="7" value="${mode.octave_range?.[1] ?? 5}"></label>
    </div>
    <div class="two-col"><label class="field"><span>描述</span><input data-field="description" value="${esc(mode.description)}"></label><label class="field"><span>Bar 4 结尾策略（逗号分隔）</span><input id="bar4-strategies" value="${esc((mode.bar_4_strategies || []).join(", "))}"></label></div>
    <label class="switch"><input id="mode-enabled" type="checkbox" ${mode.enabled !== false ? "checked" : ""}> 启用此模式</label>
    <p><b>允许吉他：</b><span class="tag-row">${choices("guitar", mode.allowed_guitar_types || [])}</span></p>
    <p><b>音色方向：</b><span class="tag-row">${choices("sound", mode.allowed_sound_directions || [])}</span></p>
    <p><b>能量：</b><span class="tag-row">${choices("energy", mode.allowed_energy || [])}</span></p>
    <p><b>节奏：</b><span class="tag-row">${choices("rhythm", mode.allowed_rhythm || [])}</span></p>
    <div class="tag-row"><b>Variant：</b>${(mode.variants || []).map((item) => `<button data-variant="${item.id}" class="${item.id === active?.id ? "primary" : ""}">${esc(item.name || item.id)}</button>`).join("")} ${mode.variants.length < 4 ? '<button id="add-variant">新增 Variant</button>' : ""}</div>
    <h2>${esc(active?.name || "Variant")}</h2>
    <div id="events">${(active?.events || []).map((item, index) => eventRow(item, index)).join("")}</div>
    <div class="actions"><button id="add-event">新增音符</button><button id="delete-variant">删除当前 Variant</button></div>`;
  document.querySelectorAll("[data-field]").forEach((input) => input.oninput = () => { const key = input.dataset.field; mode[key] = input.type === "number" ? Number(input.value) : input.value; });
  document.querySelectorAll("[data-velocity]").forEach((input) => input.oninput = () => { mode.velocity_range[Number(input.dataset.velocity)] = Number(input.value); });
  document.querySelectorAll("[data-octave]").forEach((input) => input.oninput = () => { mode.octave_range[Number(input.dataset.octave)] = Number(input.value); });
  $("bar4-strategies").oninput = () => { mode.bar_4_strategies = $("bar4-strategies").value.split(",").map((value) => value.trim()).filter(Boolean); };
  $("mode-enabled").onchange = () => { mode.enabled = $("mode-enabled").checked; };
  Object.entries({ guitar: "allowed_guitar_types", sound: "allowed_sound_directions", energy: "allowed_energy", rhythm: "allowed_rhythm" }).forEach(([tag, key]) => document.querySelectorAll(`[data-tag="${tag}"]`).forEach((input) => input.onchange = () => { mode[key] = [...document.querySelectorAll(`[data-tag="${tag}"]:checked`)].map((item) => item.value); }));
  document.querySelectorAll("[data-variant]").forEach((button) => button.onclick = () => { selectedVariant = button.dataset.variant; render(); });
  $("add-event").onclick = () => { active.events.push({ step: 0, notes: ["root"], play_mode: "single", roll_time_ms: 0, duration_steps: 2, velocity_multiplier: 1, probability: 1, enabled: true, note_end_mode: "shared_end" }); render(); };
  $("add-variant")?.addEventListener("click", () => { const index = mode.variants.length + 1; const copy = JSON.parse(JSON.stringify(active)); copy.id = `${mode.id}_${String.fromCharCode(96 + index)}`; copy.name = `Variant ${String.fromCharCode(64 + index)}`; mode.variants.push(copy); selectedVariant = copy.id; render(); });
  $("delete-variant").onclick = () => { if (mode.variants.length <= 1) return; mode.variants = mode.variants.filter((item) => item.id !== active.id); selectedVariant = mode.variants[0].id; render(); };
}
function eventRow(item, index) { const notes = item.notes || (item.degree && item.degree !== "rest" ? [item.degree] : []); const rolls = ["roll_up", "roll_down"].includes(item.play_mode); return `<div class="event-row" data-event="${index}"><input data-event-field="step" type="number" min="0" max="15" value="${item.step}"><select data-event-field="notes" multiple title="和弦音，最多四个">${degrees.map((degree) => `<option value="${degree}" ${notes.includes(degree) ? "selected" : ""}>${degree}</option>`).join("")}</select><select data-event-field="play_mode">${playModes.map(([value, label]) => `<option value="${value}" ${item.play_mode === value ? "selected" : ""}>${label}</option>`).join("")}</select><label class="roll-time-wrap ${rolls ? "" : "hidden"}">Roll <input data-event-field="roll_time_ms" type="number" min="12" max="90" value="${item.roll_time_ms || 45}"> ms</label><input data-event-field="duration_steps" type="number" min="1" max="16" value="${item.duration_steps || 1}"><input data-event-field="velocity_multiplier" type="number" min="0.1" max="2" step="0.05" value="${item.velocity_multiplier || 1}"><input data-event-field="probability" type="number" min="0" max="1" step="0.05" value="${item.probability ?? 1}"><label><input data-event-field="enabled" type="checkbox" ${item.enabled !== false ? "checked" : ""}>启用</label><button data-remove-event="${index}">删除</button></div>`; }
function bindEvents() { document.querySelectorAll("[data-event]").forEach((row) => { const item = variant().events[Number(row.dataset.event)]; row.querySelectorAll("[data-event-field]").forEach((input) => input.onchange = () => { const key = input.dataset.eventField; if (key === "notes") item.notes = [...input.selectedOptions].map((option) => option.value).slice(0, 4); else item[key] = input.type === "checkbox" ? input.checked : input.type === "number" ? Number(input.value) : input.value; if (key === "play_mode") render(); }); }); document.querySelectorAll("[data-remove-event]").forEach((button) => button.onclick = () => { variant().events.splice(Number(button.dataset.removeEvent), 1); render(); }); }
async function load() { const data = await request("/api/guitar-performance-modes"); modes = data.modes || []; selectedId ||= modes[0]?.id || ""; selectedVariant ||= current()?.variants?.[0]?.id || ""; render(); bindEvents(); }
$("save").onclick = async () => { try { await request("/api/guitar-performance-modes/save", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ modes }) }); $("status").textContent = "已保存"; } catch (error) { $("status").textContent = error.message; } };
$("reset").onclick = async () => { if (!confirm("恢复 6 个默认吉他模式？")) return; const data = await request("/api/guitar-performance-modes/reset", { method: "POST" }); modes = data.modes || []; selectedId = modes[0]?.id || ""; selectedVariant = ""; render(); bindEvents(); $("status").textContent = "已恢复默认"; };
function playPreviewEvents(events, bpm) { previewAudioContext ||= new AudioContext(); const origin = previewAudioContext.currentTime + .06, secondsPerTick = 60 / bpm / 480; events.forEach((item) => { const oscillator = previewAudioContext.createOscillator(), gain = previewAudioContext.createGain(); const startTick = item.bar * 1920 + item.step * 120 + item.timing + item.offset_ticks; oscillator.type = "triangle"; oscillator.frequency.value = 440 * 2 ** ((item.pitch - 69) / 12); gain.gain.setValueAtTime(.0001, origin + startTick * secondsPerTick); gain.gain.exponentialRampToValueAtTime(Math.max(.015, item.velocity / 127 * .07), origin + startTick * secondsPerTick + .01); gain.gain.exponentialRampToValueAtTime(.0001, origin + (startTick + item.duration) * secondsPerTick); oscillator.connect(gain).connect(previewAudioContext.destination); oscillator.start(origin + startTick * secondsPerTick); oscillator.stop(origin + (startTick + item.duration) * secondsPerTick + .02); }); }
$("preview").onclick = async () => { try { const bpm = Number($("preview-bpm").value || 100); const data = await request("/api/guitar-performance-modes/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ modes, mode: current()?.id, variant: variant()?.id, guitar_type: $("preview-guitar-type").value, sound_direction: $("preview-sound").value, energy: $("preview-energy").value, rhythm: "flow", bpm, guitar_roll_amount: 1 }) }); const events = data.events || []; playPreviewEvents(events, bpm); $("preview-result").textContent = `${data.manifest?.mode_name || "Preview"} · ${data.manifest?.variant_name || ""}\n${events.map((item) => `Bar ${item.bar + 1} · Step ${item.step} · ${item.play_mode} · Roll ${item.roll_time_ms}ms · ${item.degree} · MIDI ${item.pitch} · Start ${item.bar * 1920 + item.step * 120 + item.timing + item.offset_ticks} · End ${item.bar * 1920 + item.step * 120 + item.timing + item.offset_ticks + item.duration} · 力度 ${item.velocity}`).join("\n") || "无音符"}`; } catch (error) { $("preview-result").textContent = error.message; } };
const originalRender = render; render = (...args) => { originalRender(...args); queueMicrotask(bindEvents); };
load().catch((error) => { $("status").textContent = error.message; });
