const $ = (id) => document.getElementById(id);
const tagKeys = ["emotion", "energy", "sound_direction", "rhythm"];
let instruments = [], definitions = {
  categories: ["piano", "electric_piano", "organ", "keyboard", "pad", "synth", "strings", "choir", "bell", "pluck", "nylon_guitar", "electric_guitar", "acoustic_bass", "electric_bass", "synth_bass", "sub_bass", "brass", "woodwinds", "mallet", "other"],
  tags: {
    emotion: ["深沉", "阴郁", "忧伤", "平静", "温暖", "明亮", "欢快", "激昂"],
    energy: ["静止", "高能", "流动"],
    sound_direction: ["ambient", "acoustic", "organic", "vintage", "electronic", "ethnic", "cinematic"],
    rhythm: ["sparse", "flow", "standard", "groove", "aggressive"]
  }
}, selectedId = "", audioContext = null, previewRoundRobinCursors = {};

const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (ch) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[ch]));
const noteNames = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
function midiNote(value) { const text = String(value).trim(); if (/^-?\d+$/.test(text)) return Math.max(0, Math.min(127, Number(text))); const hit = text.match(/^([A-Ga-g])([#b]?)(-?\d+)$/); if (!hit) return 60; const pc = { C: 0, "C#": 1, Db: 1, D: 2, "D#": 3, Eb: 3, E: 4, F: 5, "F#": 6, Gb: 6, G: 7, "G#": 8, Ab: 8, A: 9, "A#": 10, Bb: 10, B: 11 }[hit[1].toUpperCase() + hit[2]]; return Math.max(0, Math.min(127, (Number(hit[3]) + 1) * 12 + pc)); }
function noteName(midi) { return `${noteNames[midi % 12]}${Math.floor(midi / 12) - 1}`; }
function selected() { return instruments.find((item) => item.id === selectedId); }

async function request(url, options = {}) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.error || "请求失败"); return data; }
async function load() { const data = await request("/api/instruments"); instruments = data.instruments || []; definitions = data.definitions || definitions; populateDefinitions(); if (!selectedId && instruments[0]) selectedId = instruments[0].id; render(); }
function populateDefinitions() { $("instrument-category").innerHTML = `<option value="">未分类</option>${(definitions.categories || []).map((value) => `<option value="${value}">${value}</option>`).join("")}`; $("filter-category").innerHTML = `<option value="">全部分类</option>${(definitions.categories || []).map((value) => `<option value="${value}">${value}</option>`).join("")}`; tagKeys.forEach((key) => { $("tag-" + key).innerHTML = (definitions.tags?.[key] || []).map((value) => `<label class="choice"><input type="checkbox" value="${value}" /><span>${value}</span></label>`).join(""); }); renderKeyboard(); }
function blank(role = "foundation") { return { id: "", name: "未命名乐器", description: "", track_role: role, category: role === "bass" ? "electric_bass" : "electric_piano", performance_engine: "foundation", guitar_type: "", enabled: true, priority: 100, version: "1.0.0", tag_rules: Object.fromEntries(tagKeys.map((key) => [key, []])), playback: { gain_db: 0, pan: 0, attack_ms: role === "bass" ? 3 : 5, release_ms: role === "bass" ? 20 : 30, polyphony: role === "bass" ? 8 : 32, velocity_curve: "linear", transpose: 0 }, sample_zones: [] }; }
function render() { renderList(); renderForm(); renderZones(); }
function renderList() { const search = $("instrument-search").value.toLowerCase(), role = $("filter-role").value, category = $("filter-category").value, enabledOnly = $("filter-enabled").checked; const rows = instruments.filter((item) => (!search || item.name.toLowerCase().includes(search)) && (!role || item.track_role === role) && (!category || item.category === category) && (!enabledOnly || item.enabled)); $("instrument-list").innerHTML = rows.length ? rows.map((item) => `<button class="instrument-card ${item.id === selectedId ? "active" : ""}" data-instrument="${item.id}"><b>${escapeHtml(item.name)}</b><span>${escapeHtml(item.track_role)} · ${escapeHtml(item.category || "未分类")}</span><small>${item.sample_zones.length} 个 Zone · 优先级 ${item.priority} · ${item.enabled ? "启用" : "停用"}</small></button>`).join("") : `<p class="hint">没有符合条件的乐器</p>`; document.querySelectorAll("[data-instrument]").forEach((button) => button.addEventListener("click", () => { selectedId = button.dataset.instrument; render(); })); }
function setTags(item) { tagKeys.forEach((key) => { const values = new Set(item.tag_rules?.[key] || []); document.querySelectorAll(`#tag-${key} input`).forEach((input) => input.checked = values.has(input.value)); }); }
function renderForm() { const item = selected() || blank(); $("instrument-name").value = item.name; $("instrument-description").value = item.description; $("instrument-role").value = item.track_role; $("instrument-category").value = item.category; $("performance-engine").value = item.performance_engine || "foundation"; $("guitar-type").value = item.guitar_type || "nylon"; $("guitar-type-wrap").classList.toggle("hidden", $("performance-engine").value !== "guitar_single_note"); $("instrument-priority").value = item.priority; $("instrument-version").value = item.version; $("instrument-enabled").checked = item.enabled; $("playback-gain").value = item.playback.gain_db; $("playback-pan").value = item.playback.pan; $("playback-attack").value = item.playback.attack_ms; $("playback-release").value = item.playback.release_ms; $("playback-polyphony").value = item.playback.polyphony; $("playback-curve").value = item.playback.velocity_curve; $("playback-transpose").value = item.playback.transpose; setTags(item); $("foundation-preview").classList.toggle("hidden", item.track_role !== "foundation"); $("bass-preview").classList.toggle("hidden", item.track_role !== "bass"); }
function checked(key) { return [...document.querySelectorAll(`#tag-${key} input:checked`)].map((input) => input.value); }
function collect() { const existing = selected() || blank($("instrument-role").value), engine = $("performance-engine").value; return { ...existing, name: $("instrument-name").value.trim() || "未命名乐器", description: $("instrument-description").value.trim(), track_role: $("instrument-role").value, category: $("instrument-category").value, performance_engine: engine, guitar_type: engine === "guitar_single_note" ? $("guitar-type").value : "", priority: Number($("instrument-priority").value || 100), version: $("instrument-version").value.trim() || "1.0.0", enabled: $("instrument-enabled").checked, tag_rules: Object.fromEntries(tagKeys.map((key) => [key, checked(key)])), playback: { gain_db: Number($("playback-gain").value || 0), pan: Number($("playback-pan").value || 0), attack_ms: Number($("playback-attack").value || 0), release_ms: Number($("playback-release").value || 0), polyphony: Number($("playback-polyphony").value || 1), velocity_curve: $("playback-curve").value, pitch_bend_range: 2, transpose: Number($("playback-transpose").value || 0) } }; }
async function save() { const item = collect(); const data = await request(item.id ? `/api/instruments/${item.id}` : "/api/instruments", { method: item.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(item) }); selectedId = data.instrument.id; $("library-status").textContent = "已保存"; await load(); return selected(); }
function renderZones() { const item = selected(); const zones = item?.sample_zones || []; $("zone-table").innerHTML = zones.length ? zones.map((zone) => `<tr data-zone="${zone.id}"><td><b>${escapeHtml(zone.name)}</b><small>${escapeHtml(zone.file_name)}</small></td><td><input data-key="root_midi_note" value="${noteName(zone.root_midi_note)}" /></td><td><input data-key="low" value="${noteName(zone.note_range.low)}" /></td><td><input data-key="high" value="${noteName(zone.note_range.high)}" /></td><td><small>dyn${zone.velocity_layer || 1}<br>${zone.velocity_range.low}-${zone.velocity_range.high}</small></td><td><small>${zone.round_robin_group ? `rr${zone.round_robin_index || 1}` : "-"}</small></td><td><input data-key="gain_db" type="number" step="0.5" value="${zone.gain_db}" /></td><td><input data-key="pan" type="number" min="-1" max="1" step="0.1" value="${zone.pan}" /></td><td><input data-key="enabled" type="checkbox" ${zone.enabled ? "checked" : ""} /></td><td><button data-action="preview-zone">试听</button><button data-action="save-zone">保存</button><button data-action="delete-zone">删除</button></td></tr>`).join("") : `<tr><td colspan="10" class="hint">上传 WAV 后会在这里显示音域映射。</td></tr>`; document.querySelectorAll("[data-action]").forEach((button) => button.addEventListener("click", () => zoneAction(button))); }
async function zoneAction(button) { const row = button.closest("tr"), item = selected(), zone = item.sample_zones.find((entry) => entry.id === row.dataset.zone); const action = button.dataset.action; if (action === "preview-zone") return playZone(zone, zone.root_midi_note); if (action === "delete-zone") { await request(`/api/instruments/${item.id}/zones/${zone.id}`, { method: "DELETE" }); return load(); } const zoneData = { ...zone, root_midi_note: midiNote(row.querySelector('[data-key="root_midi_note"]').value), note_range: { low: midiNote(row.querySelector('[data-key="low"]').value), high: midiNote(row.querySelector('[data-key="high"]').value) }, gain_db: Number(row.querySelector('[data-key="gain_db"]').value || 0), pan: Number(row.querySelector('[data-key="pan"]').value || 0), enabled: row.querySelector('[data-key="enabled"]').checked }; await request(`/api/instruments/${item.id}/zones/${zone.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(zoneData) }); await load(); }
function selectZone(note, velocity) {
  const zones = (selected()?.sample_zones || []).filter((zone) => zone.enabled);
  const inside = zones.filter((zone) => zone.note_range.low <= note && note <= zone.note_range.high && zone.velocity_range.low <= velocity && velocity <= zone.velocity_range.high);
  const usable = inside.length ? inside : zones;
  const score = (zone) => [Math.abs(zone.root_midi_note - note), Math.abs(((zone.velocity_range.low + zone.velocity_range.high) / 2) - velocity)];
  const best = usable.reduce((current, zone) => {
    const value = score(zone);
    return !current || value[0] < current[0] || (value[0] === current[0] && value[1] < current[1]) ? value : current;
  }, null);
  const preferred = usable.filter((zone) => score(zone)[0] === best?.[0] && score(zone)[1] === best?.[1]);
  const rr = preferred.filter((zone) => zone.round_robin_group);
  if (rr.length > 1) {
    rr.sort((a, b) => Number(a.round_robin_index || 1) - Number(b.round_robin_index || 1) || a.id.localeCompare(b.id));
    const key = `${note}:${rr[0].round_robin_group}:${rr[0].velocity_layer || 1}`;
    const index = previewRoundRobinCursors[key] || 0;
    previewRoundRobinCursors[key] = index + 1;
    return rr[index % rr.length];
  }
  return preferred.sort((a, b) => a.id.localeCompare(b.id))[0];
}
async function playZone(zone, targetNote) { if (!zone?.file_url) return; const velocity = Number($("preview-velocity").value); audioContext ||= new AudioContext(); const buffer = await (await fetch(zone.file_url)).arrayBuffer(); const source = audioContext.createBufferSource(), gain = audioContext.createGain(), panner = audioContext.createStereoPanner(); source.buffer = await audioContext.decodeAudioData(buffer); source.playbackRate.value = 2 ** ((targetNote + Number(selected().playback.transpose || 0) - zone.root_midi_note) / 12); gain.gain.value = Math.pow(10, (Number(selected().playback.gain_db || 0) + Number(zone.gain_db || 0)) / 20) * (velocity / 127); panner.pan.value = Math.max(-1, Math.min(1, Number(selected().playback.pan || 0) + Number(zone.pan || 0))); source.connect(gain).connect(panner).connect(audioContext.destination); source.start(); source.stop(audioContext.currentTime + 1.5); $("preview-readout").textContent = `目标 ${noteName(targetNote)} · Zone ${zone.name} · 根音 ${noteName(zone.root_midi_note)} · 速率 ${source.playbackRate.value.toFixed(3)} · 力度 ${velocity}`; }
function renderKeyboard() { $("mini-keyboard").innerHTML = Array.from({ length: 61 }, (_, index) => { const midi = 24 + index; return `<button class="key ${noteNames[midi % 12].includes("#") ? "black" : "white"}" data-note="${midi}" title="${noteName(midi)}">${noteName(midi)}</button>`; }).join(""); document.querySelectorAll("[data-note]").forEach((button) => button.addEventListener("click", () => { const note = Number(button.dataset.note), zone = selectZone(note, Number($("preview-velocity").value)); playZone(zone, note); })); }
function chordNotes(symbol) { const match = String(symbol).match(/^([A-G])([#b]?)(.*)$/); if (!match) return []; const pc = midiNote(`${match[1]}${match[2]}3`) % 12, quality = match[3], root = 48 + ((pc - 48) % 12), minor = quality.startsWith("m") && !quality.startsWith("maj"), intervals = [0, minor ? 3 : 4, 7]; if (/maj7|maj9/.test(quality)) intervals.push(11); else if (/7|m9|m11|m7|13/.test(quality)) intervals.push(10); if (/9/.test(quality)) intervals.push(14); return intervals.map((interval) => root + interval); }
function bind() { $("new-instrument").addEventListener("click", () => { selectedId = ""; render(); }); $("save-instrument").addEventListener("click", async () => { try { await save(); } catch (error) { $("library-status").textContent = error.message; } }); $("duplicate-instrument").addEventListener("click", async () => { if (!selected()) return; const data = await request(`/api/instruments/${selectedId}/duplicate`, { method: "POST" }); selectedId = data.instrument.id; await load(); }); $("delete-instrument").addEventListener("click", async () => { if (!selected() || !confirm("删除该乐器及其上传的 Zone 文件？")) return; await request(`/api/instruments/${selectedId}`, { method: "DELETE" }); selectedId = ""; await load(); }); $("auto-map").addEventListener("click", async () => { if (!selected()) return; await request(`/api/instruments/${selectedId}/auto-map`, { method: "POST" }); await load(); }); $("zone-file").addEventListener("change", async (event) => { const file = event.target.files[0]; if (!file) return; try { let item = selected(); if (!item) { $("library-status").textContent = "正在创建乐器"; item = await save(); } const form = new FormData(); form.append("file", file); await request(`/api/instruments/${item.id}/upload-sample`, { method: "POST", body: form }); event.target.value = ""; $("library-status").textContent = "WAV 已上传"; await load(); } catch (error) { event.target.value = ""; $("library-status").textContent = error.message; } }); ["instrument-search", "filter-role", "filter-category", "filter-enabled"].forEach((id) => $(id).addEventListener("input", renderList)); $("instrument-role").addEventListener("change", renderForm); $("preview-velocity").addEventListener("input", () => $("preview-velocity-value").textContent = $("preview-velocity").value); $("play-chord").addEventListener("click", () => chordNotes($("chord-symbol").value).forEach((note, index) => setTimeout(() => playZone(selectZone(note, Number($("preview-velocity").value)), note), index * 40))); document.querySelectorAll("[data-bass-pattern]").forEach((button) => button.addEventListener("click", () => { const root = midiNote($("bass-root").value), pattern = button.dataset.bassPattern; const notes = pattern === "fifth" ? [root, root + 7] : pattern === "octave" ? [root, root + 12] : pattern === "pulse" ? [root, root, root, root] : [root]; notes.forEach((note, index) => setTimeout(() => playZone(selectZone(note, Number($("preview-velocity").value)), note), index * 180)); })); }
bind();
$("performance-engine").addEventListener("change", () => $("guitar-type-wrap").classList.toggle("hidden", $("performance-engine").value !== "guitar_single_note"));
$("instrument-category").addEventListener("change", () => { const category = $("instrument-category").value; if (category === "nylon_guitar" || category === "electric_guitar") { $("performance-engine").value = "guitar_single_note"; $("guitar-type").value = category === "nylon_guitar" ? "nylon" : "electric"; $("guitar-type-wrap").classList.remove("hidden"); } });
populateDefinitions();
render();
load().catch(() => $("library-status").textContent = "预览模式：上传与保存请打开本地服务页面");
